### ISSUE TITLE
Query Input Element of Unexpected Size

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j-browser#1184]
### Description

UI issue with the query input component - it seems like there is too much padding at the bottom sometimes

### Reproduce Steps

in Neo4j Desktop, run a browser guide with some queries that are few lines tall and many lines tall. 
Example: 

`:play https://guides.neo4j.com/graph-examples/northwind-recommendation-engine/graph_guide`

First query (big):

<img width="916" alt="Screen Shot 2020-09-03 at 3 39 08 PM" src="https://user-images.githubusercontent.com/2731744/92159619-b48dfd80-edfb-11ea-8a86-7e335e8adac2.png">

Second query (small)

<img width="906" alt="Screen Shot 2020-09-03 at 3 39 22 PM" src="https://user-images.githubusercontent.com/2731744/92159649-be176580-edfb-11ea-9cd5-d52d22e15ac7.png">

Why so much empty space after the text?

### Expected Behavior

The size of the query component should either stay the same and force me to change its shape, or expand in size to accommodate the size of the query

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Mac Catalina
| Web browser    |  neo4j desktop
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  |
| Neo4j          | Neo4j 4.1.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.

**Comment by akollegger** [comment]
Hi @whatSocks ,

Could you provide some more detail about the problem you're experiencing? What are you trying to do, how is the behavior you've observed preventing work, and what user benefits do you see from different behavior?

> For enhancements or other issues, please describe in as much detail as possible how the app should be changed and how this would benefit users/developers.


Thanks,
Andreas

**Comment by cybersam** [comment]
I strongly second the request to have the input panel at the top of the browser be reasonably sized (either automatically, or -- probably even better -- as determined by the user via a draggable control). Whenever I try to enter a query of even average complexity, I find that the input panel is constrained to show only about 6 lines at a time, with no way to adjust the panel height.

Even though the entire window is much taller, almost all that height is devoted to _other_ panels showing the results of prior queries (and each of those other panels is taller than the input panel, for some reason).

The most important panel -- the one I am working on at the moment -- should be at tall as it needs to be (or as the user desires it to be). My suggestion is to have the heights of all panels be adjustable by the user.

**Comment by akollegger** [comment]
Hi @cybersam ,

Thanks for sharing some details about how you work with Browser. I love these observations! And, I'm intrigued by a few particular things you've said.

> I usually have to edit the query elsewhere and then paste it into the panel. This is not a good user experience.

What if you didn't have to paste it back into Browser? Do you use VS code or something similar for non-Neo4j work? I ask because one way to think about the bad experience you've described here is whether it could be better than just using Neo4j Browser by itself. VSCode (and emacs, vi, intellij, etc) is always going to have a way better editing experience than we could hope to have within Browser. What if you could stay in VS-Code, edit your Cypher _and_ run it without switching back to Browser? Imagine table results and graph visualization were possible. Or, the Browser side you could let you "open in external editor" and that editor could "view results in Neo4j Browser". 

> The most important panel -- the one I am working on at the moment -- should be at tall as it needs to be (or as the user desires it to be). My suggestion is to have the heights of all panels be adjustable by the user.

Neo4j Browser is a glorified Cypher REPL. Well, we want it to be glorious. :) Like any REPL, the iterative flow of type something, hit return, see results only gets you so far. At some point you want vi or emacs or pico and a file-based flow rather than interactive mode. But emacs isn't bash and bash doesn't become emacs. With Browser we are trying to bake many cakes and eat them, too. Editing is one.

The approach we're working towards in Browser is to recognize switching between bash and emacs. The idea is that when you do have a single query flow you're grooving on you could stay within a single frame which could be most of the screen size. Currently that is possible but kindof pointless because you get more screen to work on the query but the result produces another frame, and also hides the editor. It's a terrible workflow. 

Instead, every single frame (at any size it happens to be) will be editable and re-runnable. The full-size frame will have a section for editing and another section for results. _That_ layout will absolutely allow the split to be resizable (and left/right or top/bottom arrangeable). It'll be as if we had an "emacs mode" without changing the fundamental repl-ness of Browser. It's more that "this frame has become emacs and I can stay here". 

> Even though the entire window is much taller, almost all that height is devoted to other panels showing the results of prior queries (and each of those other panels is taller than the input panel, for some reason).

It drives me nuts that all frames take up so much space, regardless of their content. The uniformity helps enormously inside the frame when there is a lot of UI and content. But it's a bit wasteful when the result of a query is 'true' and frustrating when the result is an error that shifts focus away from the source of the error and the place to fix it. 

Seeing previous queries is helpful when you're running multiple similar queries and you want to compare results. That's not super-smooth right now with all the UI chrome in the way, but something we're also going to work to improve. 

Other cakes we bake include:

- the unixy `man` pages of `:help`, which are hard to find, aren't searchable, could be better integrated in-context to queries
- the interactive presentation decks of `:play` guides, which also are hard to find, aren't searchable, are hard to create, produce a lot of extra frames that lose flow and focus and, ironically, aren't great when put in fullscreen presentation mode
- another bullet for guides: mini-applications with form-based input, controls, and component-based output areas that are user editable in a super-old-school Hypercard way
- system monitoring, which is very basic, aching for more insight into what is going on within the DBMS
- user management, which is also a bit basic, just enough to work

"How do people do X in bash?" is very much the question I ask myself for both how and how-much Browser should do. That maps very directly to the client-side `:` commands for specialized activities, making each frame a mini-app that _can_ and should specialize for the command that invoked it. Cypher is basically one of those commands (imagine prefixing all cypher queries with a `:run`). Even things like parameters for queries are sortof like environment variables, if you squint at them.

It's the tool that's available everywhere Neo4j is available, used by many different people for many different reasons. We do want it to be a great Cypher editor, but without making it exclusively a Cypher editor. 

I'm sharing all that because, really, I share your goals and frustrations. I hope knowing how we're approaching Browser's evolution helps, and also that (I think/hope) how you'd like to use Browser will be possible, though maybe not precisely as you've asked. 

Cheers, 
ABK

**Comment by whatSocks** [comment]
@akollegger - not sure how to re-state my original post since I think it already answers those questions, but I'll give it a shot. I don't know if the input field is supposed to be resizing at all. Right now either the bug is that the input field is resizing improperly, or that the input field is resizing:

In Neo4j Desktop using Neo4j 4.1.0, play a browser guide that includes queries of different line counts, like this one:

```
:play https://guides.neo4j.com/graph-examples/northwind-recommendation-engine/graph_guide
``` 

Steps for playing the guide:

* run the play command
* pin the result 
* tap the 'next' arrow until cypher appears
* tap on the cypher code block (let's call this code block A) within the guide
* see view the cypher you just tapped in the input field at the top of Neo4j browser
* run the cypher, or don't run the cypher
* tap the 'next' arrow in the guide until another cypher query appears (let's call this code block B)
* tap the next cypher query in the guide
* see view the cypher you just tapped in the input field at the top of Neo4j browser

Expected: 
After this step: "tap the next cypher query in the guide"
The input field should either not resize (forcing the user to scroll) or resize based on the contents of the cypher from tapping the guide - so when I tap code block B, the height of the input field should make sense for contents of code block B. 

Actual:
The input field is of a size that would make sense based on the height not of its current contents (code block B), but of the cypher inserted into the input field by the guide on a previous tapping of the cypher (code block A).


How does this harm the user

* if the input field is improperly sized in the "input field is too small for the input" the user can't read the input
* if the input field is improperly sized in the "input field is too large for the input" direction the browser feels broken

**Comment by OskarDamkjaer** [comment]
The editor sizing has behaviour changed in #1211 and will be released this week. Feel free to bring up thoughts on the updated look and feel in a new issue, closing this as it is out dated.
