### ISSUE TITLE
Delete a node / relationships from the neo4j browser

### ISSUE THREAD

**Issue by oskarhane** [neo4j/neo4j-browser#123]
_From @thomasfr on February 25, 2014 15:33_

Whats missing at the moment is an easy way to remove a node and / or relationships from within the neo4j web browser. The browser should also add the query to the log, so one can see which query was executed to delete the node / relationship.

_Copied from original issue: neo4j/neo4j#2044_

**Comment by oskarhane** [comment]
_From @matt-way on April 29, 2014 1:13_

That would be a great addition.

**Comment by oskarhane** [comment]
_From @maciej-sz on June 4, 2014 20:2_

+1

**Comment by logless** [comment]
+1

**Comment by InverseFalcon** [comment]
+1

**Comment by oskarhane** [comment]
This is not likely to be added to the Neo4j Browser.

**Comment by jsmars** [comment]
+1 on this feature. I don't see why you wouldn't want to implement this. I often find myself using the browser as I would phpmyadmin, and when developing new projects it would be worth a lot to be able to delete and even edit nodes manually from within the browser without having to write queries for each action, since they change a lot while debugging.
