### ISSUE TITLE
Bookmarking queries (bad experience)

### ISSUE THREAD

**Issue by RayLuxembourg** [neo4j/neo4j-browser#1462]
**Description:**
When bookmarking my queries, I go through a very bad experience.
My query is saved without name === to the query and then I have to rename it.
1. I have to click on  the icon
2. go to Favorites 
3. Find where my new query is (COMPLEX when you have many)
4. Click the menu
5. choose to rename
6. insert new name

**Expectation**
1. Click the bookmark Icon
2. Popup with input displays to insert name or description for the query.
3. Save by clicking ENTER on the keyboard or with mouse somehow.

**Comment by OskarDamkjaer** [comment]
We had this behaviour before and changed it due to people being annoyed with having to name their query every time (even if it was only pressing enter). What is suggest you do is prepend your query with a comment before saving it, there you're able to set a name. 

https://user-images.githubusercontent.com/10564538/124482756-ea986700-dda9-11eb-9fa2-8d2317194f4e.mp4

**Comment by RayLuxembourg** [comment]
> We had this behaviour before and changed it due to people being annoyed with having to name their query every time (even if it was only pressing enter). What is suggest you do is prepend your query with a comment before saving it, there you're able to set a name.
> 
>  CleanShot.2021-07-05.at.15.58.00.mp4

thanks this should do it.
