### ISSUE TITLE
For nodes and relationships, in Rows view, show Label and Relationship Type

### ISSUE THREAD

**Issue by ADTC** [neo4j/neo4j-browser#169]
Can the **Rows** view show Labels for nodes and Relationship Types for relationships?

This is applicable when the query returns nodes and relationships (as opposed to queries that return properties in a tabular format).

**Comment by oskarhane** [comment]
Sorry, due to response format limitations we cannot do that.  
You would have to return those values yourself:

```
MATCH (n:Label) RETURN n, labels(n)
```

**Comment by ADTC** [comment]
But the **Graph** view is able to show me the Labels and Relationship Types. Can't the same logic apply in the **Rows** view?

**Comment by ADTC** [comment]
@oskarhane hope to receive a clarification

**Comment by oskarhane** [comment]
@ADTC The rows and the visualization views use different results format returned from the sever.  
The 'rows' response format is quite poor and moving forward moving away from the REST API to Bolt, all this will be replaced with one single response format from the server (since with Bolt we actually get types like Node etc).
