### ISSUE TITLE
Browser buttons text and table are changed places

### ISSUE THREAD

**Issue by vikingUnet** [neo4j/neo4j-browser#1845]
Neo4j version: 4.3.19
Operating system: Ubuntu 20.04.5 LTS
API/Driver: http://localhost:7474/browser/ tutorial "Movie Graph Guide", step 5
Steps to reproduce
Expected behavior
buttons table must show table and text must show text
Actual behavior
![image](https://user-images.githubusercontent.com/31891790/199741642-990a134e-dbab-425a-ae6b-e6876366864a.png)
![image](https://user-images.githubusercontent.com/31891790/199741799-1f05942a-d4d9-43f6-8ed7-efbfb91e68b8.png)

**Comment by eijawerner** [comment]
It is actually correct, it is just confusing since the Table only shows one single cell which is containing the json representation of cloudAtlas since it only returned one element that matched. If you run this query for example `MATCH (m:Movie<-[r:ACTED_IN]-(p:Person)RETURN m.title, r.roles, p.name;` then it is more clear that it is a table in the Table view (and yes the name Text is a bit confusing because it is also a kind of a table but constructed out of ascii instead of proper html elements).
