### ISSUE TITLE
"WebSocket connection failure." when bolt is on an unexpected port

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/neo4j-browser#346]
I run across this a lot due to doing dev work with Docker;

When I choose different external ports for both `7474` and `7687`, the first time I browse to `http://IP:NEW_PORT/browser/`, I cannot log in.

Pressing log in gives the error 

```WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3```

It's obviously defaulting to bolt communication on port `7687`

I just open the settings, disable bolt, and move on, but it might be helpful to fail gracefully:

"We can't contact the Bolt interface. We are defaulting to HTTP on the current port, but just know that Bolt is better. (To use Bolt, give the Web UI the current port in the settings on the left. URI > Bolt)"

**Comment by oskarhane** [comment]
We now use a discovery service to discover the Bolt port. As long as your server side config for advertised address is set correctly, the correct Bolt port will be chosen.

The reason for that message is that we (as in js in the web browser) don't know the reason why it fails, just as the message says.

Anyway, thanks for your suggestions, I agree that we could be more informative.

**Comment by arthcras** [comment]
07:46:40 Connecting to bolt://7687/neo4j...
07:46:40 Connection failed!
07:46:40 WebSocket connection failure. Due to security constraints in your web browser, the reason for the
07:46:40 failure is not available to this Neo4j Driver. Please use your browsers development console to
07:46:40 determine the root cause of the failure. Common reasons include the database being unavailable,
07:46:40 using the wrong connection URL or temporary network problems. If you have enabled encryption,
07:46:40 ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket
07:46:40 `readyState` is: 3
how can i solve the issue above?

**Comment by arthcras** [comment]
In Neo4j 3.0 and its implementation of the Bolt protocol, if a remote browser connects to Neo4j (http://<remote_neo4j_host>:7474) and attempts to authenticate, the following error may be encountered:

WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket readyState is: 3

This error can be resolved by editing the file $NEO4J_HOME/conf/neo4j.conf and uncommenting:

# To have Bolt accept non-local connections, uncomment this line:
dbms.connector.bolt.address=0.0.0.0:7687

this is what i found but how do i do that to edit the file, kindly clarify

**Comment by anonymous31173** [comment]
your $NEO4J_HOME is what /etc/ is. you can change directory to /etc/neo4j. Then use the following command:
sudo nano neo4j.conf
then modify whatever you want and save it by pressing ctrl+o. enter
ctrl + x to exit edit mode.
