### ISSUE TITLE
Creating nodes labeled Country doesn't show any attributes

### ISSUE THREAD

**Issue by michael-simons** [neo4j/neo4j-browser#806]
Neo4j Browser version: 3.1.14
Neo4j Server version: 3.4.1 (community)
Safari 11.1.2

Run

`CREATE (n:Country {name:'Germany'}), (m:aCountry {name:'Sweden'}) RETURN n,m`

Two nodes are created, but only one is displayed as expected, though both having a `name` property.

It works in Chrome but not Safari.
See attached screen shots.

Safari:

<img width="1179" alt="safari" src="https://user-images.githubusercontent.com/526383/43364893-9a382990-92f1-11e8-84f2-35cbaaacdfc8.png">

Expected graph:

<img width="1052" alt="chrome" src="https://user-images.githubusercontent.com/526383/43364897-a49e63d6-92f1-11e8-89d4-d204b39da2c0.png">

Safari highlights both `Count` and `Try` in the editor

**Comment by oskarhane** [comment]
This has to do with the styling of the viz, called GraSS. 
It tries to be clever and auto detect what caption to put in the node, but it seems like it didn't catch it for the `Country`.
Try `:style reset` to reset styles, or click on the node label in the legend to be able to chose what to display in the nodes.
The styling is stored in your web browser local storage which is why it looks different in different web browsers.
