### ISSUE TITLE
After initial load, the fake "cursor" in the input panel is flashing, even though the panel does not have focus.

### ISSUE THREAD

**Issue by allthedrones** [neo4j/neo4j-browser#904]
### Description

After Browser loads, the fake cursor block in the input panel flashes *even though the input does not have focus*. This is a queue to the user that they can begin typing Cypher and expect their input to appear in the panel, but they cannot.

### Reproduce Steps
* Load Browser, observe that query bar has a flashing cursor block
* Without interacting with the page, begin typing
* Observe that your keystrokes are not reflected in the query panel, but may be reflected elsewhere (like the browser address bar).

### Expected Behavior
Either, focus the query panel upon page load so that keystrokes will land there, OR, don't render a flashing cursor until the panel actually has focus, and render some placeholder text instead to inform users that this is where they should focus and *then* type.

### Current Behavior
See description & repro steps.

**Comment by OskarDamkjaer** [comment]
That sure is an unwanted behaviour, however I'm unable to reproduce this in our latest version of browser. I've tried safari, edge, firefox and chrome. If the problem is still there on the [latest build](https://s3-eu-west-1.amazonaws.com/ux.neotechnology.com/assets/neo4j-browser-latest/index.html) for you, do re-open this issue with instructions on how to reproduce it!

**Comment by dustykline** [comment]
Agree that this is resolved in later versions.
