### ISSUE TITLE
Unexpected Output

### ISSUE THREAD

**Issue by Tarunjot-Singh** [neo4j/neo4j-browser#923]
| software name  | version
| ---------------|----------
|                |  
| OS             |  Mac mojave
| Web browser    |  Chrome
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | Chrome (Latest Version)
| Neo4j          | 3.5.3

### Description
If we return a relationship from version 3.0.3 we get a graph view while in version 3.5.3 if we return a relationship we dont get a graph view, By default it shows table view. 

### Reproduce Steps
Lets take a simple example `MATCH (n :Person{ name: 'Tarun' })-[r:KNOWS]-(c) RETURN r` 
If i run the Above Query in Neo4j Enterprise Version 3.0.3 its gives a Graph View, but in Neo4j Enterprise Version 3.5.3, by default it give the table view.
![Screenshot 2019-04-08 at 11 36 57 AM](https://user-images.githubusercontent.com/42371705/55702716-0c50eb00-59f5-11e9-8bf8-6f0f9cf4523f.png)

Expected Behavior
I was Expecting a Graph View.

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

**Comment by oskarhane** [comment]
Hi and thanks for the report @Tarunjot-Singh.
This is however expected since the move to use Bolt rather than Neo4j:s HTTP transaction endpoint produce different results.
HTTP has a so called graph result format available which does some magic and return things that the user didn't ask for whereas you need to be more explicit in Bolt.
To get similar results in Neo4j 3.1+ (I think that's when we started using bolt), try returning the path:

`MATCH p=(n :Person{ name: 'Tarun' })-[r:KNOWS]-(c) RETURN p`
