### ISSUE TITLE
Can't set parameters in the same command as query

### ISSUE THREAD

**Issue by NightMachinary** [neo4j/neo4j-browser#961]
I am trying to run this:
```cypher
:param username => "a_r_khojasteh" ;
    MATCH (user:User {username: $username})
    MATCH user_out=(user)-->()
    return user_out ;
```
But the browser can't seem to be able to parse `:param username => "a_r_khojasteh" ;`.
Note that this *does* work in `cypher-shell`.

The browser doesn't support multiple parameters in a single command at all:
```cypher
:param username => "a_r_khojasteh"
:param y => "kja"
```

**Comment by oskarhane** [comment]
@NightMachinary Thanks for opening this issue.
neo4j-browser does support multiple params, you just need to enable the editor to work in "multi-statement" mode. You enable that in the settings sidebar.
After that your first code snippet should work just fine.

Note that when you run multiple statements you don't see the output as you are used to. In neo4j-browser the current state of multi-statement is to setup your environment with multiple statements so that you after that can execute queries and examine the results, one by one.

**Comment by NightMachinary** [comment]
Can’t you add an option to show the result of the last statement in a query?
That’d enable me to write a high level API for my graph on top of cypher.
